### ISSUE TITLE
Limit use of Google services as much as possible

### ISSUE THREAD

**Issue by jbelien** [OpenLabsHackerspace/OSCAL2020-website#2]
Hello everyone,

The new website is looking great!
I see that [Zeppelin](https://github.com/gdg-x/zeppelin) uses some Google services. The main one is Google Maps for the [venue location](http://gdg-x.github.io/zeppelin/#location-map).

I'm pretty sure you already planned to get rid of any slightest piece of Google code but if you need help, feel free to ask :)

**Comment by sidorelauku** [comment]
Hey @jbelien,

Yes there are some third parties there at the moment as we just cloned the code from Zeppelin theme, but will be removed all before making the website visible in OSCAL domain. Thanks for issue and your help :)

**Comment by rskikuli** [comment]
@sidorelauku can you please update @jbelien with this?

**Comment by rskikuli** [comment]
Pingity ping @sidorelauku :)

**Comment by AnXh3L0** [comment]
I'll check this out today and remove the tracking 3rd parties :)

**Comment by sidorelauku** [comment]
I had removed most of the third parties. @AnXh3L0  I would appreciate your help with this :)

**Comment by rskikuli** [comment]
Closing this for the moment. If @AnXh3L0 would find the time to work on this would be nice.
