### ISSUE TITLE
Copyright and license notes

### ISSUE THREAD

**Issue by rskikuli** [OpenLabsHackerspace/OSCAL2020-website#3]
I propose to have the following notes on the footer: 

- © 2014 - 2020 by Open Labs Albania. Website structure Based on Project Zeppelin;
- It needs to be clear how people can contribute. I think a note like 'improve this site' might help;
- proposed note for content license:  All site content, unless otherwise noted, is licensed on a Creative Commons BY-SA 4.0 International (https://creativecommons.org/licenses/by-sa/4.0/) by Open Labs Albania. Trademarks are property of their respective owners.

Don't forget to add respective links.

**Comment by sidorelauku** [comment]
@rskikuli  I updated footer. Please check and let me know what you think about it.

**Comment by rskikuli** [comment]
Looking good! Closing this.

**Comment by rskikuli** [comment]
I would just add, if possible the text 'improve this website' with the link to the repo.
