### ISSUE TITLE
'Become a Speaker' button needs proper redirection

### ISSUE THREAD

**Issue by rskikuli** [OpenLabsHackerspace/OSCAL2020-website#4]
The link to 'Become a Speaker' button that appears when one scrolls down, does not redirect to the right link. 
![image](https://user-images.githubusercontent.com/17770262/73596527-f03dad80-4522-11ea-8751-5fc107909ca1.png)

R.S

**Comment by sidorelauku** [comment]
Thanks @rskikuli . This is fixed now.

**Comment by rskikuli** [comment]
Many thanks. Closing
