### ISSUE TITLE
About Tirana: adding links

### ISSUE THREAD

**Issue by rskikuli** [OpenLabsHackerspace/OSCAL2020-website#7]
There are no active links from this page. I think it would help if there are some links directing to other pages, such as wikiVoyage etc.

**Comment by sidorelauku** [comment]
@rskikuli I have added links to the actual content. 
I will let you know when the page will be fully finished.

**Comment by sidorelauku** [comment]
@rskikuli if you do not have any other proposal for links, you can close this. I already added some links there.
